### ISSUE TITLE
Problems writing MP3s with version 3+

### ISSUE THREAD

**Issue by rhyatt** [Jehoel/TeslaTags#10]
Here's what I've worked out:
* Using versions 1 or 2, everything works.
* Using versions 3, 4, or 5, all FLACs are saved correctly, but all attempts to save MP3 files results in the following error in TeslaTags_Log.txt
Error	Could not save file: Unable to cast object of type 'TagLib.NonContainer.Tag' to type 'TagLib.Id3v2.Tag'.
* There are no Windows events generated (101 or otherwise).

I know this is not a lot to go on.  Ping me if I can help narrow it down further!

**Comment by Jehoel** [comment]
I've now fixed this for release 6. This is an embarrassing bug actually because I would have caught it if I did more thorough testing before release.
