### ISSUE TITLE
Remember Music Root

### ISSUE THREAD

**Issue by frankvg** [Jehoel/TeslaTags#7]
My music root is not in the Windows default music folder. Would be nice if it remembered the music root that I set after exit/return.  A minor plus would be to also understand libraries.

**Comment by frankvg** [comment]
Hi,

 

Great points and I now agree not worth doing. I’ve been doing testing on the PC, and I’m also not a big fan of libraries and don’t really use them. Just happen to test it and saw it didn’t’ seem to work.  Perhaps a slightly larger dialog explaining libraries are not supported as they don’t work with USB flash drives, but may not be worth the bother.

Best regards,

Frank.

**Comment by Jehoel** [comment]
Closing. I just pushed the commits that get config save/load working. Config is saved when the Start button is pressed and when the main window is closed.
